MESSSAGE sip:cucu@sms.iptel.org SIP/2.0
Via: SIP/2.0/UDP 195.37.78.169:11457
From: "bogdan" <sip:bogdan@iptel.org>;tag=0e99b1e7-ff50-4875-94ef-4ca5c27e2705
To: <sip:cucu@sms.iptel.org>..Call-ID: 02b1191c-447e-4bd0-b771-c039fc0d9d84@195.37.78.169
CSeq: 7 MESSAGE
Contact: <sip:195.37.78.169:11457>
User-Agent: Windows RTC/1.0
Content-Type: text/plain; charset=UTF-8;msgr=WAAtAE0ATQBTAC0ASQBNAC0ARgBvAHIAbQBhAHQAOgAgAEYATgA9AE0AUwAlADIAMABTAGgAZQBsAGwAJQAyADAARABsAGcAOwAgAEUARgA9ADsAIABDAE8APQAwADsAIABDAFMAPQAwADsAIABQAEYAPQAwAA0ACgANAAoA
Content-Length: 4
dfss

