REGISTER sip:iptel.org SIP/2.0
Via: SIP/2.0/UDP 195.37.77.103:9
From: sip:shawn.lipman@iptel.org;tag=7618c7618^
To: sip:blb@iptel.org;tag=
Call-Id: 1023638012-reg@24.114.138.250
Cseq: 61 REGISTER
Contact: <sip:shawn.lipman@24.114.138.250:5061;LINEID=bf07b2caa09525f72d4364642a0e287d>
Expires: 3
Authorization: Digest realm="iptel.org", nonce="3d6f6863000000005b60307d4fa699b2fa22957393754da0", uri="sip:iptel.org", response="82a055bbfe0aeec5f5f882e5a66a90eb", algorithm="MD5"
Content-Length: 0
Accept-Language: en
Supported: sip-cc, sip-cc-01, timer
User-Agent: Pingtel/2.0.0 (WinNT)
Date: Sun, 09 Jul 2002 16:22:37 GMT

