include ../../Makefile.defs
auto_gen=
NAME=purple.so
LIBS= 

DEFS+=-I/usr/lib/glib-2.0/include -I/usr/include/glib-2.0 \
		-I/usr/include/libxml2
LIBS+=-lglib-2.0 -lpurple -lxml2


include ../../Makefile.modules
