.\" $Id$
.TH ser.cfg 5 15.07.2002 ser "Sip Express Router" 
.\" Process with
.\" groff -man -Tascii ser.cfg.5 
.\"
.SH NAME
ser.cfg \- ser configuration file
.SH SYNOPSIS
.I /etc/ser/ser.cfg
.SH DESCRIPTION
.B ser
reads the configuration data from
.I /etc/ser/ser.cfg
(or the file specified with
.B \-f
on the command line).
The file contains global configuration parameters, module loading commands and the script that will be executed for each received request. Lines starting with
.B #
or enclosed in
.B /* ... */
are interpreted as comments.
.PP
This manual page is incomplete. For further information please read
.I /usr/share/doc/README.

.SH FILES
.bL
.I /etc/ser/ser.cfg
.br

.SH AUTHORS
This manual page was written by Andrei Pelinescu - Onciul <pelinescu-onciul@fokus.gmd.de>.
.br
.B ser
was written by Andrei Pelinescu - Onciul, Bogdan Iancu, Daniel-Constantin Mierla,
Jan Janak, Jiri Kuthan, Nils Ohlmeier, Ricardo Baratto, Stelios Sidiroglou-Douskos.

.SH SEE ALSO
.BR ser.cfg(5)
.PP
Full documentation on ser, including configuration guidelines, FAQs and
licensing conditions, is available at
http://www.iptel.org/ser/.
.PP
Report bugs at https://developer.berlios.de/bugs/?func=addbug&group_id=480 .
For help/support, write an email to <serhelp@iptel.org>.

