.\" $Id$
.TH ser.cfg 5 15.07.2002 ser "Sip Express Router" 
.\" Process with
.\" groff -man -Tascii ser.cfg.5 
.\"
.SH NAME
ser.cfg \- ser configuration file
.SH SYNOPSIS
.I /etc/ser/ser.cfg
.SH DESCRIPTION
.B ser
reads the configuration data from
.I /etc/ser/ser.cfg
(or the file specified with
.B \-f
on the command line).
The file contains global configuration parameters, module loading commands and the script that will be executed for each received request. Lines starting with
.B #
or enclosed in
.B /* ... */
are interpreted as comments.
.PP
This manual page is incomplete. For further information please read the
.I Ser User Guide (http://www.iptel.org/ser/admin.html).

.SH FILES
.bL
.I /etc/ser/ser.cfg
.br

.SH AUTHORS

see 
.B /usr/share/doc/ser/AUTHORS

.SH SEE ALSO
.BR ser(8)
.PP
Full documentation on ser, including configuration guidelines, FAQs and
licensing conditions, is available at
.I http://www.iptel.org/ser/.
.PP
For reporting  bugs see
.I
http://www.iptel.org/ser/bugs/.
.PP
Mailing lists:
.nf 
serusers@iptel.org - ser user community
.nf 
serdev@iptel.org - ser development, new features and unstable version

