.\" $Id$
.TH ser 8 15.07.2002 ser "Sip Express Router" 
.\" Process with
.\" groff -man -Tascii ser.8
.\"
.SH NAME
ser \- very fast and configurable sip proxy
.SH SYNOPSIS
.B ser
[
.B \-hcrRvdDEVT
] [
.BI \-f " config\-file"
] [
.BI \-l " address"
] [
.BI \-n " processes\-no"
] [
.BI \-N " tcp processes\-no"
] [
.BI \-b " max_rcv_buf_size"
] [
.BI \-m " shared_mem_size"
] [
.BI \-w " working\-dir"
] [
.BI \-t " chroot\-dir"
] [
.BI \-u " uid"
] [
.BI \-g " gid"
] [
.BI \-P " pid\-file"
] [
.BI \-i " fifo\-path"
] [
.BI \-x " socket\-path"
]

.SH DESCRIPTION
.B ser 
or
.BR Sip
.BR Express 
.BR Router 
is a very fast and configurable SIP proxy. 

.SH OPTIONS
.TP 12
.B \-h
Displays a short usage description, including all available options.
.TP
.BI \-c
Checks the config file and displays the aliases and listen interface list.
.TP
.BI \-r
Uses dns to check if it is necessary to add a "received=" field to a via.
.TP
.BI \-R
Same as 
.B \-r
but uses reverse dns.
.TP
.BI \-v
Turns on via host checking when forwarding replies.
.TP
.BI \-d
Turns on debugging, multiple
.B -d
increase the debug level.
.TP
.BI \-D
Runs ser in the foreground (it doesn't fork into daemon mode).
.TP
.BI \-E
Sends all the log messages to stderr.
.TP
.BI \-T
Disables TCP support.
.TP
.BI \-V
Displays the version number.
.TP
.BI \-f " config\-file"
Reads the configuration from 
.B " config\-file" 
(default
.I  /etc/ser/ser.cfg
).
.TP
.BI \-l " address"
Listens on the specified address/interface. Multiple 
.B \-l
mean listening on multiple addresses. The address format is 
[proto:]address[:port], where proto = udp|tcp and
address = host|ip_address|interface_name. Example: -l localhost, 
-l udp:127.0.0.1:5080, -l eth0:5062.
The default behaviour is to listen on all the ipv4 interfaces.
.TP
.BI \-n " processes\-no"
Specifies the number of children processes forked per interface (default 8).
.TP
.BI \-N " tcp processes\-no"
Specifies the number of children processes forked to handle tcp incoming connections (by default is equal to
.BI \-n
).
.TP
.BI \-b " max_rcv_buf_size"
Maximum receive buffer size which will not be exceeded by the auto-probing procedure even if the OS allows.
.TP
.BI \-m " shared_mem_size"
Size of the shared memory which will be allocated (in Megabytes).
.TP
.BI \-w " working\-dir" 
Specifies the working directory. In the very improbable event that 
.B ser 
will crash, the core file will be generated here.
.TP
.BI \-t " chroot\-dir"
Forces 
.B ser 
to chroot after reading the config file.
.TP
.BI \-u " uid"
Changes the user id under which 
.B ser
runs.
.TP
.BI \-g " gid"
Changes the group id under which 
.B ser 
runs.
.TP
.BI \-P " pid\-file"
Creates a file containing the pid of the main 
.B ser 
process.
.TP
.BI \-i " fifo\-path"
Creates a fifo, usefull for monitoring
.B ser
status.
.TP
.BI \-x " socket\-path"
Creates a unix socket, usefull for monitoring
.B ser
status ( same as
.BI \-i " fifo\-path" 
but using instead unix sockets).


.SH FILES
.PD 0
.B /usr/sbin/ser
.br
.B /etc/ser/ser.cfg
.br
.B /usr/lib/ser/modules/*
.PD
.SH AUTHORS

see 
.B /usr/share/doc/ser/AUTHORS

.SH SEE ALSO
.BR ser.cfg(5)
.PP
Full documentation on ser, including configuration guidelines, FAQs and
licensing conditions, is available at
.I http://www.iptel.org/ser/.
.PP 
For reporting  bugs see
.I
http://www.iptel.org/ser/bugs/.
.PP
Mailing lists:
.nf 
serusers@iptel.org - ser user community
.nf 
serdev@iptel.org - ser development, new features and unstable version
