.\" $Id$
.TH sip-router.cfg 5 15.07.2002 sip-router "SIP Router" 
.\" Process with
.\" groff -man -Tascii sip-router.cfg.5 
.\"
.SH NAME
sip-router.cfg \- sip-router configuration file
.SH SYNOPSIS
.I /etc/sip-router/sip-router.cfg
.SH DESCRIPTION
.B sip-router
reads the configuration data from
.I /etc/sip-router/sip-router.cfg
(or the file specified with
.B \-f
on the command line).
The file contains global configuration parameters, module loading commands and the script that will be executed for each received request. Lines starting with
.B #
or enclosed in
.B /* ... */
are interpreted as comments.
.PP
This manual page is incomplete. For further information please see documentation on page
.I  http://sip-router.org/wiki.

.SH FILES
.I /etc/sip-router/sip-router.cfg

.SH AUTHORS

see 
.B /usr/share/doc/sip-router/AUTHORS

.SH SEE ALSO
.BR sip-router(8)
.PP
Full documentation on sip-router, including configuration guidelines, FAQs and
licensing conditions, is available at
.I http://sip-router.org.
.PP
For reporting  bugs see
.I
http://sip-router.org/tracker/
.PP
Mailing lists:
.nf 
sr-users@lists.sip-router.org - SIP Router user community
.nf 
sr-dev@lists.sip-router.org - SIP Router development, new features and unstable version
