/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HI1NotificationOperations"
 * 	found in "HI1NotificationOperations.asn"
 */

#ifndef	_HI1_Operation_H_
#define	_HI1_Operation_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Notification.h"
#include "Alarm-Indicator.h"
#include "National-HI1-ASN1parameters.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HI1_Operation_PR {
	HI1_Operation_PR_NOTHING,	/* No components present */
	HI1_Operation_PR_liActivated,
	HI1_Operation_PR_liDeactivated,
	HI1_Operation_PR_liModified,
	HI1_Operation_PR_alarms_indicator,
	/* Extensions may appear below */
	HI1_Operation_PR_national_HI1_ASN1parameters
} HI1_Operation_PR;

/* HI1-Operation */
typedef struct HI1_Operation {
	HI1_Operation_PR present;
	union HI1_Operation_u {
		Notification_t	 liActivated;
		Notification_t	 liDeactivated;
		Notification_t	 liModified;
		Alarm_Indicator_t	 alarms_indicator;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		National_HI1_ASN1parameters_t	 national_HI1_ASN1parameters;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HI1_Operation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HI1_Operation;

#ifdef __cplusplus
}
#endif

#endif	/* _HI1_Operation_H_ */
#include "asn_internal.h"
