/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HI1NotificationOperations"
 * 	found in "HI1NotificationOperations.asn"
 */

#include "HI1-Operation.h"

static asn_TYPE_member_t asn_MBR_HI1_Operation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HI1_Operation, choice.liActivated),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Notification,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"liActivated"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HI1_Operation, choice.liDeactivated),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Notification,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"liDeactivated"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HI1_Operation, choice.liModified),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Notification,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"liModified"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HI1_Operation, choice.alarms_indicator),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Alarm_Indicator,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alarms-indicator"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HI1_Operation, choice.national_HI1_ASN1parameters),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_National_HI1_ASN1parameters,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"national-HI1-ASN1parameters"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_HI1_Operation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* liActivated */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* liDeactivated */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* liModified */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* alarms-indicator */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 } /* national-HI1-ASN1parameters */
};
static asn_CHOICE_specifics_t asn_SPC_HI1_Operation_specs_1 = {
	sizeof(struct HI1_Operation),
	offsetof(struct HI1_Operation, _asn_ctx),
	offsetof(struct HI1_Operation, present),
	sizeof(((struct HI1_Operation *)0)->present),
	asn_MAP_HI1_Operation_tag2el_1,
	5,	/* Count of tags in the map */
	0,
	4	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_HI1_Operation = {
	"HI1-Operation",
	"HI1-Operation",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_HI1_Operation_1,
	5,	/* Elements count */
	&asn_SPC_HI1_Operation_specs_1	/* Additional specs */
};

