/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HI2Operations"
 * 	found in "HI2Operations.asn"
 */

#ifndef	_Network_Element_Identifier_H_
#define	_Network_Element_Identifier_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"
#include "IPAddress.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Network_Element_Identifier_PR {
	Network_Element_Identifier_PR_NOTHING,	/* No components present */
	Network_Element_Identifier_PR_e164_Format,
	Network_Element_Identifier_PR_x25_Format,
	Network_Element_Identifier_PR_iP_Format,
	Network_Element_Identifier_PR_dNS_Format,
	/* Extensions may appear below */
	Network_Element_Identifier_PR_iP_Address
} Network_Element_Identifier_PR;

/* Network-Element-Identifier */
typedef struct Network_Element_Identifier {
	Network_Element_Identifier_PR present;
	union Network_Element_Identifier_u {
		OCTET_STRING_t	 e164_Format;
		OCTET_STRING_t	 x25_Format;
		OCTET_STRING_t	 iP_Format;
		OCTET_STRING_t	 dNS_Format;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		IPAddress_t	 iP_Address;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Network_Element_Identifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Network_Element_Identifier;

#ifdef __cplusplus
}
#endif

#endif	/* _Network_Element_Identifier_H_ */
#include "asn_internal.h"
