/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HI2Operations"
 * 	found in "HI2Operations.asn"
 */

#include "Network-Identifier.h"

static int
memb_operator_Identifier_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 1 && size <= 5)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_Network_Identifier_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Network_Identifier, operator_Identifier),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		memb_operator_Identifier_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"operator-Identifier"
		},
	{ ATF_POINTER, 1, offsetof(struct Network_Identifier, network_Element_Identifier),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Network_Element_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"network-Element-Identifier"
		},
};
static const ber_tlv_tag_t asn_DEF_Network_Identifier_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Network_Identifier_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* operator-Identifier */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* network-Element-Identifier */
};
static asn_SEQUENCE_specifics_t asn_SPC_Network_Identifier_specs_1 = {
	sizeof(struct Network_Identifier),
	offsetof(struct Network_Identifier, _asn_ctx),
	asn_MAP_Network_Identifier_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* Start extensions */
	3	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Network_Identifier = {
	"Network-Identifier",
	"Network-Identifier",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Network_Identifier_tags_1,
	sizeof(asn_DEF_Network_Identifier_tags_1)
		/sizeof(asn_DEF_Network_Identifier_tags_1[0]), /* 1 */
	asn_DEF_Network_Identifier_tags_1,	/* Same as above */
	sizeof(asn_DEF_Network_Identifier_tags_1)
		/sizeof(asn_DEF_Network_Identifier_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Network_Identifier_1,
	2,	/* Elements count */
	&asn_SPC_Network_Identifier_specs_1	/* Additional specs */
};

