/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HI2Operations"
 * 	found in "HI2Operations.asn"
 */

#ifndef	_Network_Identifier_H_
#define	_Network_Identifier_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Network_Element_Identifier;

/* Network-Identifier */
typedef struct Network_Identifier {
	OCTET_STRING_t	 operator_Identifier;
	struct Network_Element_Identifier	*network_Element_Identifier	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Network_Identifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Network_Identifier;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Network-Element-Identifier.h"

#endif	/* _Network_Identifier_H_ */
#include "asn_internal.h"
