LIBNAME  = xcap
OUT_NAME = lib_ser_xcap.so
OUT_TYPE = lib
INCLUDES += -I/usr/include/libxml2 -I${LOCALBASE}/include -I${LOCALBASE}/include/libxml2
LIBS     += -L${LOCALBASE}/lib -lxml2 -l_ser_cds

include ../Makefile.ser.defs

