.TH kamctl 8 20.11.2017 Kamailio "Kamailio"
.\" Process with
.\" groff -man -Tascii kamctl.8
.\"
.SH NAME
kamctl \- Kamailio control tool
.SH SYNOPSIS
.B kamctl
.BI command
[
.BI parameters
]

.SH DESCRIPTION
.B kamctl
is a shell script to control
.B Kamailio SIP Server.

It can be used to manage users, domains, aliases and other server options.


.SH COMMANDS
Run
.B kamctl help
to see the list of available commands.

.SH FILES
.PD 0
.I /etc/kamailio/kamctlrc
.br
.I /usr/local/etc/kamailio/kamctlrc
.br
.I ~/.kamctlrc
.br

.SH NOTES
.PP
Some commands become available when enabling an RPC engine or a database system
inside
.B kamctlrc
file.

.PP
For some commands, parameters can be prefixed with 's:' in order to enforce
string type (e.g., 's:123456789').

.SH AUTHORS

see
.B /usr/share/doc/kamailio/AUTHORS

.SH SEE ALSO
.BR kamailio(8),
.BR kamailio.cfg(5)
.PP
Full documentation on Kamailio is available at
.I https://www.kamailio.org

.PP
Mailing lists:

.nf
sr-users@lists.kamailio.org - Kamailio user community
.nf
sr-dev@lists.kamailio.org - Kamailio development community

