#include "timer.h"

/* jku: currently, we add all timer items in the list's tail;
   this works as long as timers have fixed values; this
   will change with variable timers (e.g., such as those
   generated by users of CPL scripts or different-size
   retransmission timers); then some searching technique
   would be good; perhaps binary starting from tail?
*/


void * timer_routine(void * attr);


/* put a new cell into a list nr. list_id within a hash_table;
  * set initial timeout
  */
void add_to_tail_of_timer_list( struct s_table* hash_table , struct timer_link* tl, int list_id , unsigned int time_out )
{
   struct timer* timer_list = &(hash_table->timers[ list_id ]);

   /* the entire timer list is locked now -- noone else can manipulate it */
   lock( timer_list->mutex );
   tl->time_out = time_out + hash_table->time;
   tl->next_tl= 0;

   if (timer_list->last_tl)
   {
       tl->prev_tl=timer_list->last_tl;
       timer_list->last_tl->next_tl = tl;
       timer_list->last_tl = tl ;
   } else {
       tl->prev_tl = 0;
       timer_list->first_tl = tl;
       timer_list->last_tl = tl;
   }
   /* give the list lock away */
   unlock( timer_list->mutex );
}




/*
  */
void insert_into_timer_list( struct s_table* hash_table , struct timer_link* tl, int list_id , unsigned int time_out )
{
   struct timer* timer_list = &(hash_table->timers[ list_id ]);
}




/* remove a cell from a list nr. list_id within a hash_table;
*/
void remove_from_timer_list( struct s_table* hash_table , struct timer_link* tl , int list_id)
{
   struct timer* timers=&(hash_table->timers[ list_id ]);

   if (tl->next_tl || tl->prev_tl || (!tl->next_tl && !tl->prev_tl && tl==timers->first_tl)   )
   {
      lock( timers->mutex );
      if ( tl->prev_tl )
         tl->prev_tl->next_tl = tl->next_tl;
      else
         timers->first_tl = tl->next_tl;
      if ( tl->next_tl )
         tl->next_tl->prev_tl = tl->prev_tl;
      else
         timers->last_tl = tl->prev_tl;
      unlock( timers->mutex );
      tl->next_tl = 0;
      tl->prev_tl = 0;
   }
}




/* remove a cell from the head of  list nr. list_id within a hash_table;
*/
struct timer_link  *remove_from_timer_list_from_head( struct s_table* hash_table, int list_id )
{
   struct timer* timers=&(hash_table->timers[ list_id ]);
   struct timer_link *tl = timers->first_tl;

   if  (tl)
   {
      lock( timers->mutex  );
      timers->first_tl = tl->next_tl;
     if (!timers->first_tl)
         timers->last_tl=0;
     else
         tl->next_tl->prev_tl = 0;
      unlock( timers->mutex );
      tl->next_tl = 0;
      tl->prev_tl = 0;
   }

   return tl;
}







void * timer_routine(void * attr)
{
   struct s_table      *hash_table = (struct s_table *)attr;
   struct timer*         timers= hash_table->timers;
   struct timeval       a_sec;
   struct timer_link* tl;
   int unsigned*         time =  &(hash_table->time);
   int                           id;


   while (1)
   {
      a_sec.tv_sec   = 1;
      a_sec.tv_usec = 0;
      select( 0 , 0 , 0 ,0 , &a_sec );
      (*time)++;
      printf("%d\n", *time);

      for( id=0 ; id<NR_OF_TIMER_LISTS ; id++ )
         while ( timers[ id ].first_tl->time_out >= *time )
         {
            tl = remove_from_timer_list_from_head( hash_table, id );
            timers[id].timeout_handler( tl->payload );
         }

   } /* while (1) */
}

