# $Id$
#
# Group Membeship checking over Radius
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=group_radius.so
LIBS=-L/usr/local/lib -lradiusclient

include ../../Makefile.modules
