# $Id: Makefile,v 1.1.1.1 2007/05/09 11:25:33 bogdan Exp $
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=drouting.so
LIBS= 
DEFS+=-DOPENSER_MOD_INTERFACE

include ../../Makefile.modules
