MESSAGE sip:+49160567535@fesarius.fokus.gmd.de SIP/2.0
Via: SIP/2.0/UDP fesarius.fokus.gmde.de:9
From: sip:bogdan@fesarius.fokus.gmd.de;tag=16df4fe56e8782ecaa5d53ae36fb9240
To: sip:dcm@fesarius.fokus.gmd.de
Call-ID: 02b1191c-447e-4bd0-b771-c039fc0d9d84@195.37.78.169
CSeq: 7 MESSAGE
Contact: <sip:195.37.78.169:11457>
User-Agent: Windows RTC/1.0
Content-Type: text/plain
Content-Length: 13

cucu
bau
miau
