INVITE sip:theCallee@iptel.org SIP/2.0
Via: SIP/2.0/UDP sipproxy.icr.a-star.edu.sg:5060;branch=QdqKUsYZOGRR+j*P
Via: SIP/2.0/UDP 137.132.31.151:58072;branch=NTg2NTIwNzUw
Max-Forwards: 68
From: sip:Acaller@icr.a-star.edu.sg:6060;tag=MTU3MT
To: sip:theCallee@iptel.org
Call-ID: 1953014-jQ4MzYwNzUw-2137014
CSeq: 123456 INVITE
Contact: <sip:Acaller@137.132.31.151:58072>
Content-Type: application/sdp
Content-Length: 153

v=0
o=User 1589702922991241424 1420814338471844940 IN IP4 137.132.31.151
s=
c=IN IP4 137.132.31.151 UNHOLD UNHOLD
m=audio 58074 RTP/AVP 0 
a=rtpmap:0 PCMU/8000
