REGISTER sip:iptel.org SIP/2.0
Via: SIP/2.0/UDP 213.20.132.141:16449
From: <sip:jiri@iptel.org>;tag=5df69a49-de80-436e-82eb-d0a991cbf744
To: <sip:jiri@iptel.org>
Call-ID: f3969dea-6401-427c-bdaf-ec92beedf8e7@213.20.132.141
CSeq: 18 REGISTER
Contact: <sip:213.20.132.141:16449>;methods="INVITE, MESSAGE, INFO, SUBSCRIBE, OPTIONS, BYE, CANCEL, NOTIFY, ACK"
User-Agent: Windows RTC/1.0
Expires: 0
Content-Length: 0
Authorization: Digest username="jiri", realm="iptel.org", algorithm="MD5", uri="sip:iptel.org", response="8791571e2a65e8e1d5ac17cc49f8a16d", nonce="3
