#
# textops example module makefile
#
#
# WARNING: do not run this directly, it should be run by the main Makefile

include ../../Makefile.defs
auto_gen=
NAME=textops.so
LIBS=

include ../../Makefile.modules

