#
# pv module makefile
#
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=pv.so
LIBS=

SERLIBPATH=../../lib
include ../../Makefile.modules
