#!/bin/bash
#
# Target dist: Debian bullseye
DIST=bullseye

rm -rf ${DIST}
cp -r debian ${DIST}

# cmake missing PostgreSQL_TYPE_INCLUDE_DIR
sed -i '/^ libpq-dev,/a\ postgresql-server-dev-all,' ${DIST}/control

# no libnats-dev
sed -i -e '/^ libnats-dev,/d' \
  -e '/^Package: kamailio-nats-modules/,/^$/d' \
  ${DIST}/control
sed -i -e '/^PACKAGE_GROUPS += nats/d' ${DIST}/rules
sed -i -e '/--EXCLUDED--/i EXTRA_EXCLUDED_MODULES += nats' ${DIST}/rules

# libwolfssl-dev < 5.2
sed -i -e '/^ libwolfssl-dev,/d' \
  -e '/^Package: kamailio-wolftls-modules/,/^$/d' \
  ${DIST}/control
sed -i -e '/^PACKAGE_GROUPS += tls_wolfssl/d' ${DIST}/rules
sed -i -e '/--EXCLUDED--/i EXTRA_EXCLUDED_MODULES += tls_wolfssl' ${DIST}/rules

# libjwt < 1.12
sed -i -e '/libjwt-dev/d' -e 's/, JWT (JSON Web Token)//' ${DIST}/control
sed -i -e '/^EXTRA_GROUPS += jwt$/d' ${DIST}/rules
wrap-and-sort -sat -d ${DIST}

# libsecp256k1-dev < 0.5
sed -i -e '/^ libsecp256k1-dev,/d' \
  -e '/^Package: kamailio-authblockchain-modules/,/^$/d' \
  ${DIST}/control
sed -i -e '/^PACKAGE_GROUPS += auth_blockchain$/d' ${DIST}/rules
sed -i -e '/--EXCLUDED--/i EXTRA_EXCLUDED_MODULES += auth_blockchain' ${DIST}/rules

# clean backports scripts
rm -rf ${DIST}/backports
exit 0
