#!/bin/sh 
#
# $Id$
#
# use to check whether ser is still responding; if not mail an alert
#


NOTIFY=sr@iptel.org
SERHOME=/home/srouter
SERDIR=$SERHOME/sip_router
TESTDIR=$SERDIR/test
BIN=$TESTDIR/sipsak
MESSAGE=$TESTDIR/sipsak.sip
SERHOST=sip:iptel.org
LOCKFILE=/var/lock/serresponse
TMP=/tmp/serresponse.$$
MAILCOMMAND=/usr/bin/mail

if [ ! -e $LOCKFILE ] ; then
	if [ ! -f $MESSAGE ] ; then
		echo "serresponse did not find the required message $MESSAGE" > $TMP
	elif [ ! -x $BIN ] ; then
		echo "serresponse did not find the required sipsak executable $BIN" > $TMP
	else
		echo "The execution of this command:" > $TMP
		echo "  $BIN -f $MESSAGE -s $SERHOST" >> $TMP
		echo "produced this output:" >> $TMP
		$BIN -f $MESSAGE -s $SERHOST >> $TMP 2>&1
		if [ $? -eq 0 ] ; then
			rm -f $TMP
		fi
	fi
	
	if [ -e $TMP ] ; then
		$MAILCOMMAND -s "serresponse failed" $NOTIFY < $TMP
		touch $LOCKFILE
		rm -f $TMP
	fi
fi
