#!/bin/sh

#ps -ef|grep '/sr'| grep -v grep
PIDS=`ps --no-headers -o "pid" -C sr`
for i in $PIDS ;  do
	ps -o "pid,user,group,euser,egroup,fuser,fgroup,args" $i
	echo "WD: `ls -ld /proc/$i/cwd`"
done

#ps  -wwwwww -o "drs,pid,user,group,euser,egroup,fuser,fgroup,args" -C sr 

mysql -h dbhost -u csps -p -e "select * from location;" csps107
