#
# db_cluster module makefile
#

include ../../Makefile.defs
auto_gen=
NAME=db_cluster.so
LIBS=

DEFS+=-DOPENSER_MOD_INTERFACE

SERLIBPATH=../../lib
SER_LIBS+=$(SERLIBPATH)/srdb1/srdb1

include ../../Makefile.modules
