/*
 * SNMPStats Module 
 * Copyright (C) 2006 SOMA Networks, INC.
 * Written by: Jeffrey Magder (jmagder@somanetworks.com)
 *
 * This file is part of Kamailio, a free SIP server.
 *
 * Kamailio is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version
 *
 * Kamailio is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301
 * USA
 *
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.9 2005/01/07 09:37:18 dts12 Exp $
 *
 * This file defines all registration and handling of all scalars defined in the
 * KAMAILIO-SIP-COMMON-MIB.  Please see KAMAILIO-SIP-COMMON-MIB for the complete
 * descriptions of the individual scalars.
 */
#ifndef KAMAILIOSIPCOMMONOBJECTS_H
#define KAMAILIOSIPCOMMONOBJECTS_H

void init_kamailioSIPCommonObjects(void);

Netsnmp_Node_Handler handle_kamailioSIPProtocolVersion;
Netsnmp_Node_Handler handle_kamailioSIPServiceStartTime;
Netsnmp_Node_Handler handle_kamailioSIPEntityType;
Netsnmp_Node_Handler handle_kamailioSIPSummaryInRequests;
Netsnmp_Node_Handler handle_kamailioSIPSummaryOutRequests;
Netsnmp_Node_Handler handle_kamailioSIPSummaryInResponses;
Netsnmp_Node_Handler handle_kamailioSIPSummaryOutResponses;
Netsnmp_Node_Handler handle_kamailioSIPSummaryTotalTransactions;
Netsnmp_Node_Handler handle_kamailioSIPCurrentTransactions;
Netsnmp_Node_Handler handle_kamailioSIPNumUnsupportedUris;
Netsnmp_Node_Handler handle_kamailioSIPNumUnsupportedMethods;
Netsnmp_Node_Handler handle_kamailioSIPOtherwiseDiscardedMsgs;

#endif /* KAMAILIOSIPCOMMONOBJECTS_H */
