# uac_redirect module makefile
#
#
# WARNING: do not run this directly, it should be run by the main Makefile

include ../../Makefile.defs
auto_gen=
NAME=uac_redirect.so
LIBS=

include ../../Makefile.modules
