#ifndef _RTPENGINE_H
#define _RTPENGINE_H

typedef enum {
	RABBITMQ_OK=1,
	RABBITMQ_ERR_CONNECT,
	RABBITMQ_ERR_CHANNEL,
	RABBITMQ_ERR_QUEUE,
	RABBITMQ_ERR_PUBLISH,
	RABBITMQ_ERR_SOCK,
	RABBITMQ_ERR_CONSUME,
	RABBITMQ_ERR_NULL,
} RABBITMQ_ENUM;

#endif
