# $Id: Makefile $
#
# XCAP client for Kamailio
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=xcap_client.so
LIBS=

DEFS+=-I$(LOCALBASE)/include

LIBS+=-L$(SYSBASE)/include/lib -L$(LOCALBASE)/lib -lcurl

include ../../Makefile.modules
