# $Id: Makefile 1515 2007-01-16 21:25:55Z bogdan_iancu $
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
include ../../Makefile.radius

auto_gen=
NAME=misc_radius.so

DEFS+=-DKAMAILIO_MOD_INTERFACE

include ../../Makefile.modules
