# $Id$
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=cpl-c.so
LIBS= -L$(LOCALBASE)/lib -L/usr/pkg/lib -lxml

include ../../Makefile.modules
