#
# uid-uri-db :: Various URI checks
#
# WARNING: do not run this directly, it should be run by the main Makefile

include ../../Makefile.defs
auto_gen=
NAME=uid_uri_db.so
LIBS=

include ../../Makefile.modules
