USE or_ser;

DROP TABLE version;
DROP TABLE acc;
DROP TABLE active_sessions;
DROP TABLE aliases;
DROP TABLE event;
DROP TABLE grp;
DROP TABLE location;
DROP TABLE missed_calls;
DROP TABLE pending;
DROP TABLE phonebook;
DROP TABLE reserved;
DROP TABLE subscriber;
DROP TABLE config;
DROP TABLE silo;
DROP TABLE domain;
DROP TABLE uri;
DROP TABLE server_monitoring;
DROP TABLE usr_preferences;
DROP TABLE usr_preferences_types;
DROP TABLE trusted;
DROP TABLE server_monitoring_agg;
DROP TABLE admin_privileges;
DROP TABLE call_forwarding;
DROP TABLE speed_dial;
DROP TABLE gw;
DROP TABLE gw_grp;
DROP TABLE lcr;

DROP DATABASE or_ser;
