# $Id$
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

# extra debug messages
DEFS+=-DDBT_EXTRA_DEBUG
 
auto_gen=
NAME=dbtext.so
LIBS=

include ../../Makefile.modules
