# $Id$
#
# Digest Authentication - Radius support
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=auth_radius.so
LIBS=-L/usr/local/lib -lradiusclient

include ../../Makefile.modules
