/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef KAMAILIONET_H
#define KAMAILIONET_H

/* function declarations */
void init_kamailioNet(void);
Netsnmp_Node_Handler handle_kamailioNetTcpConnEstablished;
Netsnmp_Node_Handler handle_kamailioNetTcpConnFailed;
Netsnmp_Node_Handler handle_kamailioNetTcpConnReset;
Netsnmp_Node_Handler handle_kamailioNetTcpConnSuccess;
Netsnmp_Node_Handler handle_kamailioNetTcpConnOpened;
Netsnmp_Node_Handler handle_kamailioNetTcpConnPassiveOpen;
Netsnmp_Node_Handler handle_kamailioNetTcpConnReject;
Netsnmp_Node_Handler handle_kamailioNetTcpEnabled;

#endif /* KAMAILIONET_H */
