#
# Presence_MWI Makefile
# 
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=presence_mwi.so
LIBS=

include ../../Makefile.modules
