.\" $Id$
.TH kamcmd 8 23.10.2012 Kamailio "kamailio" 
.\" Process with
.\" groff -man -Tascii kamcmd.8 
.\"
.SH NAME
kamcmd \- kamailio command line tool
.SH SYNOPSIS
.B kamcmd
[
.B \-h
]

.SH DESCRIPTION
.B kamcmd
is a command line to interact with
.B Kamailio SIP server
It can be used to manage users, domains, aliases and other server options.

.SH OPTIONS
.TP 12
.B \-h
display a short usage description, including all available options.

.SH AUTHORS

see 
.B /usr/share/doc/kamailio/AUTHORS

.SH SEE ALSO
.BR kamailio(8),
.BR kamailio.cfg(5)
.PP
Full documentation about kamailio is available at
.I http://www.kamailio.org/.
