#!/sbin/runscript
# Copyright 2002 Frauenhofer Gesellschaft FOKUS, Germany.
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header$

depend() {
	need net
}

start() {
	ebegin "Starting Kamailio"
	start-stop-daemon --start --quiet --pidfile /var/run/kamailio.pid \
		--exec /usr/sbin/kamailio -- -P /var/run/kamailio.pid
	eend $?
}

stop() {
	ebegin "Stopping Kamailio"
	start-stop-daemon --stop --quiet --pidfile /var/run/kamailio.pid
	eend $?
}

