#!/sbin/runscript
# Copyright 2002 Frauenhofer Gesellschaft FOKUS, Germany.
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header$

depend() {
	need net
}

start() {
	ebegin "Starting OpenSER"
	start-stop-daemon --start --quiet --pidfile /var/run/openser.pid \
		--exec /usr/sbin/openser -- -P /var/run/openser.pid
	eend $?
}

stop() {
	ebegin "Stopping OpenSER"
	start-stop-daemon --stop --quiet --pidfile /var/run/openser.pid
	eend $?
}

