#!/sbin/runscript
# Copyright 2002 Frauenhofer Gesellschaft FOKUS, Germany.
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header$

depend() {
	need net
}

start() {
	ebegin "Starting ser"
	start-stop-daemon --start --quiet --pidfile /var/run/ser.pid \
		--exec /usr/sbin/ser -- -P /var/run/ser.pid
	eend $?
}

stop() {
	ebegin "Stopping ser"
	start-stop-daemon --stop --quiet --pidfile /var/run/ser.pid
	eend $?
}

