# $Id$
#
# acc module makefile
#
#
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=acc.so
LIBS=

# uncomment the next line if you wish to enable SQL accounting
#DEFS+=-DSQL_ACC

# uncomment the next two lines if you wish to enable RADIUS accounting
#DEFS+=-DRAD_ACC
#LIBS=-L$(LOCALBASE)/lib -lradiusclient

include ../../Makefile.modules
