#
# pv_headers module makefile
#
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=pv_headers.so
LIBS=

include ../../Makefile.modules
