#
# distributed message queue system for inter-intstance communication
#
#
# WARNING: do not run this directly, it should be run by the main Makefile

include ../../Makefile.defs
auto_gen=
NAME=dmq.so
LIBS=

include ../../Makefile.modules
