# $Id$
#
# mediaproxy module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=mediaproxy.so
LIBS=

include ../../Makefile.modules

