#
# NATS module
#
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs

auto_gen=
NAME=nats.so

LIBS=-lnats -luv
DEFS+=-I$(LOCALBASE)/include -I/usr/local/include

include ../../Makefile.modules
